Implementation of Keyword Extraction in Javascript
Enoch-Chou/capstoneproject pull request #23
Opened 2020-08-28 22:02 UTC by jornichol

2020-08-31 18:29 UTC, eswarty requested changes

2020-08-31 18:29 UTC, ederski commented on project/src/main/webapp/keyword.js
> +        if ((searchQuery.length-1) == count && word.indexOf('?') != -1) {
Nit: Add spacing in `searachQuery.length - 1`

2020-08-31 18:29 UTC, ederski commented on project/src/main/webapp/keyword.js
> +function editedKeywordExtraction(userInput) {
Please add comments for each function and give them more descriptive names (e.g. datamuseKeyWordExtraction vs naiveKeywordExtraction or maybe getQuestionType is more appropriate?)

2020-08-31 18:29 UTC, ederski commented on project/src/main/webapp/script.js
> +async function keywordExtraction(userInput) {
Remove duplicate function

2020-08-31 18:29 UTC, ederski commented on project/src/main/webapp/keyword.js
> +            if (count != (searchQuery.length-1)){
Nit: Fix spacing here too

2020-09-02 21:33 UTC, brandonvu12 approved these changes

2020-09-03 16:34 UTC, ederski approved these changes

2020-09-03 21:56 UTC, merged