Implementation of keyword extraction in Java
Enoch-Chou/capstoneproject pull request #24
Opened 2020-08-28 22:07 UTC by jornichol

2020-08-31 18:31 UTC, eswarty requested changes

2020-08-31 18:31 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
This function is a bit long, can you break it up into smaller functions?

2020-08-31 18:31 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
> +            if ((splitQuery.length-1) == count && word.indexOf('?') != -1) {
Nit: Add spacing around `splitQuery.length - 1`

2020-08-31 18:31 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
> +                output = new StringBuilder();
Combine this line with line 39:
```
StringBuilder output = new StringBuilder();
```

2020-08-31 18:31 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
> +                    //resultList.add(word);
Remove commented code

2020-08-31 18:31 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
> +                    if (count != (splitQuery.length-1)){
Nit: Fix spacing here too

2020-09-02 21:32 UTC, brandonvu12 approved these changes

2020-09-03 16:42 UTC, ederski approved these changes

2020-09-03 16:42 UTC, ederski commented on project/src/main/java/com/google/sps/servlets/DatamuseServlet.java
>                  BufferedReader input = new BufferedReader(new InputStreamReader(con.getInputStream()));
These are only used inside `addToString` function, so just create them there instead of passing them as parameters.

2020-09-03 21:46 UTC, merged